---
version: '3.4'
services:
  prowlarr:
    network_mode: host
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=Etc/UTC'
    restart: unless-stopped
    ports:
      - '9696:9696'
  sonarr:
    container_name: sonarr
    image: 'linuxserver/sonarr:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=Etc/UTC'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
  radarr:
    container_name: radarr
    image: 'linuxserver/radarr:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=Etc/UTC'
